function html_entities(letter){
	
letter = letter.
replace(new RegExp('&','g'),'&amp;').
replace(new RegExp('Á','g'),'&Aacute;').
replace(new RegExp('á','g'),'&aacute;').
replace(new RegExp('Â','g'),'&Acirc;').
replace(new RegExp('â','g'),'&acirc;').
replace(new RegExp('´','g'),'&acute;').
replace(new RegExp('Æ','g'),'&AElig;').
replace(new RegExp('æ','g'),'&aelig;').
replace(new RegExp('À','g'),'&Agrave;').
replace(new RegExp('à','g'),'&agrave;').
replace(new RegExp('ℵ','g'),'&alefsym;').
replace(new RegExp('α','g'),'&alpha;').
replace(new RegExp('Α','g'),'&Alpha;').
replace(new RegExp('∧','g'),'&and;').
replace(new RegExp('∠','g'),'&ang;').
replace(new RegExp("'",'g'),'&apos;').
replace(new RegExp('å','g'),'&aring;').
replace(new RegExp('Å','g'),'&Aring;').
replace(new RegExp('≈','g'),'&asymp;').
replace(new RegExp('Ã','g'),'&Atilde;').
replace(new RegExp('ã','g'),'&atilde;').
replace(new RegExp('Ä','g'),'&Auml;').
replace(new RegExp('ä','g'),'&auml;').
replace(new RegExp('„','g'),'&bdquo;').
replace(new RegExp('Β','g'),'&Beta;').
replace(new RegExp('β','g'),'&beta;').
replace(new RegExp('¦','g'),'&brvbar;').
replace(new RegExp('•','g'),'&bull;').
replace(new RegExp('∩','g'),'&cap;').
replace(new RegExp('Ç','g'),'&Ccedil;').
replace(new RegExp('ç','g'),'&ccedil;').
replace(new RegExp('¸','g'),'&cedil;').
replace(new RegExp('¢','g'),'&cent;').
replace(new RegExp('Χ','g'),'&Chi;').
replace(new RegExp('χ','g'),'&chi;').
replace(new RegExp('ˆ','g'),'&circ;').
replace(new RegExp('♣','g'),'&clubs;').
replace(new RegExp('≅','g'),'&cong;').
replace(new RegExp('©','g'),'&copy;').
replace(new RegExp('↵','g'),'&crarr;').
replace(new RegExp('∪','g'),'&cup;').
replace(new RegExp('¤','g'),'&curren;').
replace(new RegExp('‡','g'),'&Dagger;').
replace(new RegExp('†','g'),'&dagger;').
replace(new RegExp('⇓','g'),'&dArr;').
replace(new RegExp('↓','g'),'&darr;').
replace(new RegExp('°','g'),'&deg;').
replace(new RegExp('Δ','g'),'&Delta;').
replace(new RegExp('δ','g'),'&delta;').
replace(new RegExp('♦','g'),'&diams;').
replace(new RegExp('÷','g'),'&divide;').
replace(new RegExp('é','g'),'&eacute;').
replace(new RegExp('É','g'),'&Eacute;').
replace(new RegExp('ê','g'),'&ecirc;').
replace(new RegExp('Ê','g'),'&Ecirc;').
replace(new RegExp('È','g'),'&Egrave;').
replace(new RegExp('è','g'),'&egrave;').
replace(new RegExp('∅','g'),'&empty;').
replace(new RegExp(' ','g'),'&emsp;').
replace(new RegExp(' ','g'),'&ensp;').
replace(new RegExp('Ε','g'),'&Epsilon;').
replace(new RegExp('ε','g'),'&epsilon;').
replace(new RegExp('≡','g'),'&equiv;').
replace(new RegExp('Η','g'),'&Eta;').
replace(new RegExp('η','g'),'&eta;').
replace(new RegExp('Ð','g'),'&ETH;').
replace(new RegExp('ð','g'),'&eth;').
replace(new RegExp('ë','g'),'&euml;').
replace(new RegExp('Ë','g'),'&Euml;').
replace(new RegExp('€','g'),'&euro;').
replace(new RegExp('∃','g'),'&exist;').
replace(new RegExp('ƒ','g'),'&fnof;').
replace(new RegExp('∀','g'),'&forall;').
replace(new RegExp('½','g'),'&frac12;').
replace(new RegExp('¼','g'),'&frac14;').
replace(new RegExp('¾','g'),'&frac34;').
replace(new RegExp('⁄','g'),'&frasl;').
replace(new RegExp('Γ','g'),'&Gamma;').
replace(new RegExp('γ','g'),'&gamma;').
replace(new RegExp('≥','g'),'&ge;').
replace(new RegExp('>','g'),'&gt;').
replace(new RegExp('⇔','g'),'&hArr;').
replace(new RegExp('↔','g'),'&harr;').
replace(new RegExp('♥','g'),'&hearts;').
replace(new RegExp('…','g'),'&hellip;').
replace(new RegExp('í','g'),'&iacute;').
replace(new RegExp('Í','g'),'&Iacute;').
replace(new RegExp('Î','g'),'&Icirc;').
replace(new RegExp('î','g'),'&icirc;').
replace(new RegExp('¡','g'),'&iexcl;').
replace(new RegExp('Ì','g'),'&Igrave;').
replace(new RegExp('ì','g'),'&igrave;').
replace(new RegExp('ℑ','g'),'&image;').
replace(new RegExp('∞','g'),'&infin;').
replace(new RegExp('∫','g'),'&int;').
replace(new RegExp('Ι','g'),'&Iota;').
replace(new RegExp('ι','g'),'&iota;').
replace(new RegExp('¿','g'),'&iquest;').
replace(new RegExp('∈','g'),'&isin;').
replace(new RegExp('ï','g'),'&iuml;').
replace(new RegExp('Ï','g'),'&Iuml;').
replace(new RegExp('κ','g'),'&kappa;').
replace(new RegExp('Κ','g'),'&Kappa;').
replace(new RegExp('λ','g'),'&lambda;').
replace(new RegExp('Λ','g'),'&Lambda;').
replace(new RegExp('⟨','g'),'&lang;').
replace(new RegExp('«','g'),'&laquo;').
replace(new RegExp('←','g'),'&larr;').
replace(new RegExp('⇐','g'),'&lArr;').
replace(new RegExp('⌈','g'),'&lceil;').
replace(new RegExp('“','g'),'&ldquo;').
replace(new RegExp('≤','g'),'&le;').
replace(new RegExp('⌊','g'),'&lfloor;').
replace(new RegExp('∗','g'),'&lowast;').
replace(new RegExp('◊','g'),'&loz;').
replace(new RegExp('‎','g'),'&lrm;').
replace(new RegExp('‹','g'),'&lsaquo;').
replace(new RegExp('‘','g'),'&lsquo;').
replace(new RegExp('<','g'),'&lt;').
replace(new RegExp('¯','g'),'&macr;').
replace(new RegExp('—','g'),'&mdash;').
replace(new RegExp('µ','g'),'&micro;').
replace(new RegExp('·','g'),'&middot;').
replace(new RegExp('−','g'),'&minus;').
replace(new RegExp('μ','g'),'&mu;').
replace(new RegExp('Μ','g'),'&Mu;').
replace(new RegExp('∇','g'),'&nabla;').
replace(new RegExp('','g'),'&nbsp;').
replace(new RegExp('–','g'),'&ndash;').
replace(new RegExp('≠','g'),'&ne;').
replace(new RegExp('∋','g'),'&ni;').
replace(new RegExp('¬','g'),'&not;').
replace(new RegExp('∉','g'),'&notin;').
replace(new RegExp('⊄','g'),'&nsub;').
replace(new RegExp('Ñ','g'),'&Ntilde;').
replace(new RegExp('ñ','g'),'&ntilde;').
replace(new RegExp('Ν','g'),'&Nu;').
replace(new RegExp('ν','g'),'&nu;').
replace(new RegExp('Ó','g'),'&Oacute;').
replace(new RegExp('ó','g'),'&oacute;').
replace(new RegExp('Ô','g'),'&Ocirc;').
replace(new RegExp('ô','g'),'&ocirc;').
replace(new RegExp('œ','g'),'&oelig;').
replace(new RegExp('Œ','g'),'&OElig;').
replace(new RegExp('Ò','g'),'&Ograve;').
replace(new RegExp('ò','g'),'&ograve;').
replace(new RegExp('‾','g'),'&oline;').
replace(new RegExp('Ω','g'),'&Omega;').
replace(new RegExp('ω','g'),'&omega;').
replace(new RegExp('Ο','g'),'&Omicron;').
replace(new RegExp('ο','g'),'&omicron;').
replace(new RegExp('⊕','g'),'&oplus;').
replace(new RegExp('∨','g'),'&or;').
replace(new RegExp('ª','g'),'&ordf;').
replace(new RegExp('º','g'),'&ordm;').
replace(new RegExp('Ø','g'),'&Oslash;').
replace(new RegExp('ø','g'),'&oslash;').
replace(new RegExp('õ','g'),'&otilde;').
replace(new RegExp('Õ','g'),'&Otilde;').
replace(new RegExp('⊗','g'),'&otimes;').
replace(new RegExp('ö','g'),'&ouml;').
replace(new RegExp('Ö','g'),'&Ouml;').
replace(new RegExp('¶','g'),'&para;').
replace(new RegExp('∂','g'),'&part;').
replace(new RegExp('‰','g'),'&permil;').
replace(new RegExp('⊥','g'),'&perp;').
replace(new RegExp('φ','g'),'&phi;').
replace(new RegExp('Φ','g'),'&Phi;').
replace(new RegExp('Π','g'),'&Pi;').
replace(new RegExp('π','g'),'&pi;').
replace(new RegExp('ϖ','g'),'&piv;').
replace(new RegExp('±','g'),'&plusmn;').
replace(new RegExp('£','g'),'&pound;').
replace(new RegExp('″','g'),'&Prime;').
replace(new RegExp('′','g'),'&prime;').
replace(new RegExp('∏','g'),'&prod;').
replace(new RegExp('∝','g'),'&prop;').
replace(new RegExp('Ψ','g'),'&Psi;').
replace(new RegExp('ψ','g'),'&psi;').
replace(new RegExp('"','g'),'&quot;').
replace(new RegExp('√','g'),'&radic;').
replace(new RegExp('⟩','g'),'&rang;').
replace(new RegExp('»','g'),'&raquo;').
replace(new RegExp('→','g'),'&rarr;').
replace(new RegExp('⇒','g'),'&rArr;').
replace(new RegExp('⌉','g'),'&rceil;').
replace(new RegExp('”','g'),'&rdquo;').
replace(new RegExp('ℜ','g'),'&real;').
replace(new RegExp('®','g'),'&reg;').
replace(new RegExp('⌋','g'),'&rfloor;').
replace(new RegExp('Ρ','g'),'&Rho;').
replace(new RegExp('ρ','g'),'&rho;').
replace(new RegExp('‏','g'),'&rlm;').
replace(new RegExp('›','g'),'&rsaquo;').
replace(new RegExp('’','g'),'&rsquo;').
replace(new RegExp('‚','g'),'&sbquo;').
replace(new RegExp('Š','g'),'&Scaron;').
replace(new RegExp('š','g'),'&scaron;').
replace(new RegExp('⋅','g'),'&sdot;').
replace(new RegExp('§','g'),'&sect;').
replace(new RegExp('','g'),'&shy;').
replace(new RegExp('Σ','g'),'&Sigma;').
replace(new RegExp('σ','g'),'&sigma;').
replace(new RegExp('ς','g'),'&sigmaf;').
replace(new RegExp('∼','g'),'&sim;').
replace(new RegExp('♠','g'),'&spades;').
replace(new RegExp('⊂','g'),'&sub;').
replace(new RegExp('⊆','g'),'&sube;').
replace(new RegExp('∑','g'),'&sum;').
replace(new RegExp('¹','g'),'&sup1;').
replace(new RegExp('²','g'),'&sup2;').
replace(new RegExp('³','g'),'&sup3;').
replace(new RegExp('⊃','g'),'&sup;').
replace(new RegExp('⊇','g'),'&supe;').
replace(new RegExp('ß','g'),'&szlig;').
replace(new RegExp('τ','g'),'&tau;').
replace(new RegExp('Τ','g'),'&Tau;').
replace(new RegExp('∴','g'),'&there4;').
replace(new RegExp('Θ','g'),'&Theta;').
replace(new RegExp('θ','g'),'&theta;').
replace(new RegExp('ϑ','g'),'&thetasym;').
replace(new RegExp(' ','g'),'&thinsp;').
replace(new RegExp('þ','g'),'&thorn;').
replace(new RegExp('Þ','g'),'&THORN;').
replace(new RegExp('˜','g'),'&tilde;').
replace(new RegExp('×','g'),'&times;').
replace(new RegExp('™','g'),'&trade;').
replace(new RegExp('ú','g'),'&uacute;').
replace(new RegExp('Ú','g'),'&Uacute;').
replace(new RegExp('↑','g'),'&uarr;').
replace(new RegExp('⇑','g'),'&uArr;').
replace(new RegExp('Û','g'),'&Ucirc;').
replace(new RegExp('û','g'),'&ucirc;').
replace(new RegExp('ù','g'),'&ugrave;').
replace(new RegExp('Ù','g'),'&Ugrave;').
replace(new RegExp('¨','g'),'&uml;').
replace(new RegExp('ϒ','g'),'&upsih;').
replace(new RegExp('Υ','g'),'&Upsilon;').
replace(new RegExp('υ','g'),'&upsilon;').
replace(new RegExp('Ü','g'),'&Uuml;').
replace(new RegExp('ü','g'),'&uuml;').
replace(new RegExp('℘','g'),'&weierp;').
replace(new RegExp('ξ','g'),'&xi;').
replace(new RegExp('Ξ','g'),'&Xi;').
replace(new RegExp('Ý','g'),'&Yacute;').
replace(new RegExp('ý','g'),'&yacute;').
replace(new RegExp('¥','g'),'&yen;').
replace(new RegExp('ÿ','g'),'&yuml;').
replace(new RegExp('Ÿ','g'),'&Yuml;').
replace(new RegExp('ζ','g'),'&zeta;').
replace(new RegExp('Ζ','g'),'&Zeta;').
replace(new RegExp('‍','g'),'&zwj;').
replace(new RegExp('‌','g'),'&zwnj;');
return letter;
}